version: "3"
services:
    mysql_knex:
        container_name: planner_database
        hostname: planner_database
        image: mysql
        restart: always
        command:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --innodb_force_recovery=0
        volumes:
            - <rota para o diretório backup>:/var/lib/mysql
        ports:
            - 3030:3030
        
        environment:
            MYSQL_ROOT_PASSWORD: senha
            MYSQL_DATABASE: planner_database
          
            MYSQL_PASSWORD: senha
            MYSQL_TCP_PORT: 3030
            TZ: America/Sao_Paulo
    